# Cambiar db por localhost:
spring.datasource.url=jdbc:postgresql://localhost:5432/sicat_sf?currentSchema=sicat
spring.datasource.username=sicat_user
spring.datasource.password=sicat_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Agrega esta línea para evitar timeouts intentando adivinar el dialecto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=sicat
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080